[2024-04-22T17:33:43.152+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T17:33:43.171+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:33:43.175+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:33:43.176+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-22T17:33:43.183+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): greet> on 2024-04-21 00:00:00+00:00
[2024-04-22T17:33:43.190+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10194) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T17:33:43.189+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v06', 'greet', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpg75g5n05']
[2024-04-22T17:33:43.191+0000] {standard_task_runner.py:63} INFO - Started process 10195 to run task
[2024-04-22T17:33:43.191+0000] {standard_task_runner.py:91} INFO - Job 365: Subtask greet
[2024-04-22T17:33:43.213+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-22T17:33:43.253+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v06' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-04-22T17:33:43.254+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-22T17:33:43.264+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-22T17:33:43.264+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: greet() missing 1 required positional argument: 'age'
[2024-04-22T17:33:43.277+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v06, task_id=greet, execution_date=20240421T000000, start_date=20240422T173343, end_date=20240422T173343
[2024-04-22T17:33:43.287+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 365 for task greet (greet() missing 1 required positional argument: 'age'; 10195)
[2024-04-22T17:33:43.332+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-22T17:33:43.366+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:33:43.369+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-22T17:35:19.180+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T17:35:19.194+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:35:19.198+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:35:19.198+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-22T17:35:19.203+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): greet> on 2024-04-21 00:00:00+00:00
[2024-04-22T17:35:19.207+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10259) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T17:35:19.207+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v06', 'greet', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '368', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmphmdwrtbu']
[2024-04-22T17:35:19.208+0000] {standard_task_runner.py:63} INFO - Started process 10260 to run task
[2024-04-22T17:35:19.209+0000] {standard_task_runner.py:91} INFO - Job 368: Subtask greet
[2024-04-22T17:35:19.230+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-22T17:35:19.265+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v06' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-04-22T17:35:19.265+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-22T17:35:19.278+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-22T17:35:19.279+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 30, in greet
    age = ti.xcom_ull(taskids="get_age",key="age")
          ^^^^^^^^^^^
AttributeError: 'TaskInstance' object has no attribute 'xcom_ull'. Did you mean: 'xcom_pull'?
[2024-04-22T17:35:19.284+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v06, task_id=greet, execution_date=20240421T000000, start_date=20240422T173519, end_date=20240422T173519
[2024-04-22T17:35:19.289+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 368 for task greet ('TaskInstance' object has no attribute 'xcom_ull'; 10260)
[2024-04-22T17:35:19.309+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-22T17:35:19.321+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:35:19.321+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-22T17:36:14.279+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T17:36:14.292+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:36:14.296+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:36:14.296+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-22T17:36:14.301+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): greet> on 2024-04-21 00:00:00+00:00
[2024-04-22T17:36:14.305+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10296) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T17:36:14.304+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v06', 'greet', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp0kx_dowl']
[2024-04-22T17:36:14.306+0000] {standard_task_runner.py:63} INFO - Started process 10297 to run task
[2024-04-22T17:36:14.306+0000] {standard_task_runner.py:91} INFO - Job 371: Subtask greet
[2024-04-22T17:36:14.328+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-22T17:36:14.370+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v06' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-04-22T17:36:14.371+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-22T17:36:14.384+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-22T17:36:14.384+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 30, in greet
    age = ti.xcom_pull(taskids="get_age",key="age")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'taskids'
[2024-04-22T17:36:14.389+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v06, task_id=greet, execution_date=20240421T000000, start_date=20240422T173614, end_date=20240422T173614
[2024-04-22T17:36:14.393+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 371 for task greet (TaskInstance.xcom_pull() got an unexpected keyword argument 'taskids'; 10297)
[2024-04-22T17:36:14.408+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-22T17:36:14.416+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:36:14.417+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-22T17:38:50.468+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T17:38:50.489+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:38:50.493+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:38:50.493+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-22T17:38:50.500+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): greet> on 2024-04-21 00:00:00+00:00
[2024-04-22T17:38:50.508+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10393) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T17:38:50.509+0000] {standard_task_runner.py:63} INFO - Started process 10394 to run task
[2024-04-22T17:38:50.508+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v06', 'greet', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpzcalinx5']
[2024-04-22T17:38:50.510+0000] {standard_task_runner.py:91} INFO - Job 374: Subtask greet
[2024-04-22T17:38:50.541+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v06.greet scheduled__2024-04-21T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-22T17:38:50.620+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v06' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-04-22T17:38:50.621+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-22T17:38:50.643+0000] {logging_mixin.py:188} INFO - Hello World! My name is Jerry Fridman and I am 24 yeasrs old.
[2024-04-22T17:38:50.643+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-22T17:38:50.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-22T17:38:50.652+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_v06, task_id=greet, execution_date=20240421T000000, start_date=20240422T173850, end_date=20240422T173850
[2024-04-22T17:38:50.695+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-22T17:38:50.704+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:38:50.704+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
